apiVersion: v1
kind: Service
metadata:
    name: "kdiwd4cluster-ff3b"
    labels:
        app: "kdiwd4cluster-ff3b"
spec:
    type: LoadBalancer
    ports:
    - port: 3030
      targetPort: 3030
      protocol: TCP
      name: http
    selector:
        app: "kdiwd4cluster-ff3b"