# Vagrant.configure("2") do |config|
#   config.vm.provider "docker" do |d|
#     d.image = "ubuntu:22.04"
#     d.name = "my-ubuntu"
#     d.create_args = ["-i", "-d"]
#   end
# end

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.build_args = ["-t", "my-ubuntu"]
    d.name = "my-ubuntu"
    d.create_args = ["-i", "-d"]
  end
end